name: Embed code in README

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  embed-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: refs/heads/${{ github.ref_name }}

      - name: Embed code into README
        uses: programmer290399/markdown-embed-code@main
        with:
          markdown: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Synchronizing README"
          silent: true